# Generated by Django 3.2.24 on 2024-02-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Прошел активацию')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Служебный аккаунт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accelerometer_1', models.FloatField(verbose_name='Акселерометр 1')),
                ('accelerometer_2', models.FloatField(verbose_name='Акселерометр 2')),
                ('accelerometer_3', models.FloatField(verbose_name='Акселерометр 3')),
                ('hyroscope_1', models.FloatField(verbose_name='Гироскоп 1')),
                ('hyroscope_2', models.FloatField(verbose_name='Гироскоп 2')),
                ('hyroscope_3', models.FloatField(verbose_name='Гироскоп 3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
